class CharactersService {
    getCharacters() {
        var characters = [{
                character_id: 1,
                character_name: 'Frendat Smeltfoot',
                character_race: 'Gnome: Deep (Svirfneblin)',
                character_class: 'Artificer',
                character_build: 'Alchemist',
                character_max_level: 10,
            },
            {
                character_id: 2,
                character_name: 'Thurlow Smith',
                character_race: 'Human',
                character_class: 'Artificer',
                character_build: 'Armorer (UA)',
                character_max_level: 10,
            },
            {
                character_id: 3,
                character_name: "Fenphina d'Sivis",
                character_race: 'Gnome: Mark of Scribing',
                character_class: 'Artificer',
                character_build: 'Artillerist',
                character_max_level: 10,
            },
            {
                character_id: 4,
                character_name: 'Jespatys Neldastar',
                character_race: 'Dragonborn: Draconblood',
                character_class: 'Artificer',
                character_build: 'Battle Smith',
                character_max_level: 10,
            },
            {
                character_id: 5,
                character_name: 'Vamana Firehammer',
                character_race: 'Dwarf: Gray (Duergar)',
                character_class: 'Barbarian',
                character_build: 'Path of the Ancestral Guardian',
                character_max_level: 10,
            },
            {
                character_id: 6,
                character_name: 'Orikour Whiteforge',
                character_race: 'Dwarf: Mountain',
                character_class: 'Barbarian',
                character_build: 'Path of the Battlerager',
                character_max_level: 10,
            },
            {
                character_id: 7,
                character_name: 'Talon Silvermane',
                character_race: 'Shifter: Beasthide',
                character_class: 'Barbarian',
                character_build: 'Path of the Beast (UA)',
                character_max_level: 10,
            },
            {
                character_id: 8,
                character_name: 'Amethyst Whitestone',
                character_race: 'Genasi: Earth',
                character_class: 'Barbarian',
                character_build: 'Path of the Berserker',
                character_max_level: 10,
            },
            {
                character_id: 9,
                character_name: 'Celestine Windwalker',
                character_race: 'Human: Variant',
                character_class: 'Barbarian',
                character_build: 'Path of the Storm Herald',
                character_max_level: 10,
            },
            {
                character_id: 10,
                character_name: 'Urodak Skullcleaver',
                character_race: 'Orc of Exandria',
                character_class: 'Barbarian',
                character_build: 'Path of the Totem Warrior',
                character_max_level: 10,
            },
            {
                character_id: 11,
                character_name: 'Orithyra Waterwolf',
                character_race: 'Simic Hybrid',
                character_class: 'Barbarian',
                character_build: 'Path of the Wild Soul (UA)',
                character_max_level: 10,
            },
            {
                character_id: 12,
                character_name: 'Victor Ironfist',
                character_race: 'Warforged',
                character_class: 'Barbarian',
                character_build: 'Path of the Zealot',
                character_max_level: 10,
            },
            {
                character_id: 13,
                character_name: 'Arala Dawnflower',
                character_race: 'Aasimar: Protector',
                character_class: 'Bard',
                character_build: 'College of Creation (UA)',
                character_max_level: 10,
            },
            {
                character_id: 14,
                character_name: 'Ghilanna Elendhen',
                character_race: 'Half-Elf: Aquatic',
                character_class: 'Bard',
                character_build: 'College of Eloquence',
                character_max_level: 10,
            },
            {
                character_id: 15,
                character_name: 'Rexius Trannyth',
                character_race: 'Tiefling: Fierna',
                character_class: 'Bard',
                character_build: 'College of Glamour',
                character_max_level: 10,
            },
            {
                character_id: 16,
                character_name: 'Malakos Duskwalker',
                character_race: 'Tiefling: Mammon',
                character_class: 'Bard',
                character_build: 'College of Lore',
                character_max_level: 10,
            },
            {
                character_id: 17,
                character_name: 'Bruhd Arkenviir',
                character_race: 'Half-Elf: Drow',
                character_class: 'Bard',
                character_build: 'College of Swords',
                character_max_level: 10,
            },
            {
                character_id: 18,
                character_name: 'Brenwan Blademaster',
                character_race: 'Aasimar: Fallen',
                character_class: 'Bard',
                character_build: 'College of Valor',
                character_max_level: 10,
            },
            {
                character_id: 19,
                character_name: 'Damine Zangold',
                character_race: 'Tiefling: Glasya',
                character_class: 'Bard',
                character_build: 'College of Whispers',
                character_max_level: 10,
            },
            {
                character_id: 20,
                character_name: 'Selanar Fenthana',
                character_race: 'Elf: Sea',
                character_class: 'Blood Hunter',
                character_build: 'Order of the Ghostslayer',
                character_max_level: 10,
            },
            {
                character_id: 21,
                character_name: 'Vestia Blacksong',
                character_race: 'Halfling: Stout',
                character_class: 'Blood Hunter',
                character_build: 'Order of the Lycan',
                character_max_level: 10,
            },
            {
                character_id: 22,
                character_name: 'Slark Murkwater',
                character_race: 'Grung',
                character_class: 'Blood Hunter',
                character_build: 'Order of the Mutant',
                character_max_level: 10,
            },
            {
                character_id: 23,
                character_name: 'Nilga Moldfoot',
                character_race: 'Goblin',
                character_class: 'Blood Hunter',
                character_build: 'Order of the Profane Soul',
                character_max_level: 10,
            },
            {
                character_id: 24,
                character_name: "Tothin d'Medani",
                character_race: 'Half-Elf: Mark of Detection',
                character_class: 'Cleric',
                character_build: 'Arcana Domain',
                character_max_level: 10,
            },
            {
                character_id: 25,
                character_name: 'Rhaz Blackscale',
                character_race: 'Lizardfolk',
                character_class: 'Cleric',
                character_build: 'Death Domain',
                character_max_level: 10,
            },
            {
                character_id: 26,
                character_name: "Burghard d'Vadalis",
                character_race: 'Human: Mark of Handling',
                character_class: 'Cleric',
                character_build: 'Forge Domain',
                character_max_level: 10,
            },
            {
                character_id: 27,
                character_name: 'Sylric Tarmikos',
                character_race: 'Simic Hybrid',
                character_class: 'Cleric',
                character_build: 'Grave Domain',
                character_max_level: 10,
            },
            {
                character_id: 28,
                character_name: 'Gangahr Sak',
                character_race: 'Gith: Githzerai',
                character_class: 'Cleric',
                character_build: 'Knowledge Domain',
                character_max_level: 10,
            },
            {
                character_id: 29,
                character_name: "Aaliyah d'Deneith",
                character_race: 'Human: Mark of Sentinel',
                character_class: 'Cleric',
                character_build: 'Life Domain',
                character_max_level: 10,
            },
            {
                character_id: 30,
                character_name: 'Butir Aashta',
                character_race: 'Half-Orc: Mark of Finding',
                character_class: 'Cleric',
                character_build: 'Light Domain',
                character_max_level: 10,
            },
            {
                character_id: 31,
                character_name: 'Erran Meadowmaster',
                character_race: 'Firbolg',
                character_class: 'Cleric',
                character_build: 'Nature Domain',
                character_max_level: 10,
            },
            {
                character_id: 32,
                character_name: 'Thraldov Irontusk',
                character_race: 'Loxodon',
                character_class: 'Cleric',
                character_build: 'Order Domain',
                character_max_level: 10,
            },
            {
                character_id: 33,
                character_name: 'Tempest Fury',
                character_race: 'Genasi: Water',
                character_class: 'Cleric',
                character_build: 'Tempest Domain',
                character_max_level: 10,
            },
            {
                character_id: 34,
                character_name: 'Marigold Swiftpaw',
                character_race: 'Shifter: Wildhunt',
                character_class: 'Cleric',
                character_build: 'Trickery Domain',
                character_max_level: 10,
            },
            {
                character_id: 35,
                character_name: 'Ghatara Mohan',
                character_race: 'Kalashtar',
                character_class: 'Cleric',
                character_build: 'Twilight Domain (UA)',
                character_max_level: 10,
            },
            {
                character_id: 36,
                character_name: 'Theratis Wyrmsbane',
                character_race: 'Dwarf: Hill',
                character_class: 'Cleric',
                character_build: 'Unity Domain (UA)',
                character_max_level: 10,
            },
            {
                character_id: 37,
                character_name: 'Doctor Metalskin',
                character_race: 'Warforged',
                character_class: 'Cleric',
                character_build: 'War Domain',
                character_max_level: 10,
            },
            {
                character_id: 38,
                character_name: 'Kareth Aravaal',
                character_race: 'Kalashtar',
                character_class: 'Druid',
                character_build: 'Circle of Dreams',
                character_max_level: 10,
            },
            {
                character_id: 39,
                character_name: "Alluvial d'Medani",
                character_race: 'Half-Elf: Mark of Detection',
                character_class: 'Druid',
                character_build: 'Circle of Spores',
                character_max_level: 10,
            },
            {
                character_id: 40,
                character_name: "Darhana d'Vadalis",
                character_race: 'Human: Mark of Handling',
                character_class: 'Druid',
                character_build: 'Circle of the Land (Arctic)',
                character_max_level: 10,
            },
            {
                character_id: 41,
                character_name: 'Ocean Deepwater',
                character_race: 'Genasi: Water',
                character_class: 'Druid',
                character_build: 'Circle of the Land (Coast)',
                character_max_level: 10,
            },
            {
                character_id: 42,
                character_name: 'Danhorn Steamkettle',
                character_race: 'Halfling: Ghostwise',
                character_class: 'Druid',
                character_build: 'Circle of the Land (Desert)',
                character_max_level: 10,
            },
            {
                character_id: 43,
                character_name: 'Soliana Gladewalker',
                character_race: 'Elf: Aereni Wood',
                character_class: 'Druid',
                character_build: 'Circle of the Land (Forest)',
                character_max_level: 10,
            },
            {
                character_id: 44,
                character_name: "Loravyre d'Tharashk",
                character_race: 'Human: Mark of Finding',
                character_class: 'Druid',
                character_build: 'Circle of the Land (Grassland)',
                character_max_level: 10,
            },
            {
                character_id: 45,
                character_name: 'Zurc Whitefeather',
                character_race: 'Aarakocra',
                character_class: 'Druid',
                character_build: 'Circle of the Land (Mountain)',
                character_max_level: 10,
            },
            {
                character_id: 46,
                character_name: 'Drux Hungryjaw',
                character_race: 'Lizardfolk',
                character_class: 'Druid',
                character_build: 'Circle of the Land (Swamp)',
                character_max_level: 10,
            },
            {
                character_id: 47,
                character_name: "Raldarus Do'Veldrin",
                character_race: 'Half-Elf: Drow',
                character_class: 'Druid',
                character_build: 'Circle of the Land (Underdark)',
                character_max_level: 10,
            },
            {
                character_id: 48,
                character_name: "Rustle Blackfeather",
                character_race: 'Kenku',
                character_class: 'Druid',
                character_build: 'Circle of the Moon',
                character_max_level: 10,
            },
            {
                character_id: 49,
                character_name: "Daefina Burdun",
                character_race: 'Firbolg',
                character_class: 'Druid',
                character_build: 'Circle of the Shepherd',
                character_max_level: 10,
            },
            {
                character_id: 50,
                character_name: "Ohnira Nightwalker",
                character_race: 'Gith: Githzerai',
                character_class: 'Druid',
                character_build: 'Circle of the Stars (UA)',
                character_max_level: 10,
            },
            {
                character_id: 51,
                character_name: "Xanvar Emberwood",
                character_race: 'Human',
                character_class: 'Druid',
                character_build: 'Circle of Wildfire (UA)',
                character_max_level: 10,
            },
        ];

        var byProperty = function(prop) {
            return function(a, b) {
                if (typeof a[prop] == 'number') {
                    return a[prop] - b[prop];
                } else {
                    return a[prop] < b[prop] ? -1 : a[prop] > b[prop] ? 1 : 0;
                }
            };
        };

        characters.sort(byProperty('character_build'));

        return characters;
    }
}